// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://joosschalkvupfzhijid.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impvb3NzY2hhbGt2dXBmemhpamlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5Nzg2NDYsImV4cCI6MjA2MjU1NDY0Nn0.qIwox1KLPZ-3BqU6zS-3YLXgbXuF0v91MyW39U7l2XY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);